%hidden MODULE_NAME="claude_usage"
set -ogq  @catppuccin_claude_usage_icon "✽ "
set -ogqF @catppuccin_claude_usage_color "#{E:@thm_blue}"
set -ogq  @catppuccin_claude_usage_text "#(~/dots/ai_usage/claude-status.sh)"
source ~/.config/tmux/plugins/catppuccin/tmux/utils/status_module.conf
